# for updates and superuser setup, please use:
# docker-compose run python migrate
# docker-compose run

version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
      #- WISSENSLANDKARTE_DOMAINS="['www.example.com','example.com']"
    volumes:
      - "wissenslandkarte-python-data:/app/wissenslandkarte/data"
    ports: 
      - "8000:8000"
volumes:
  wissenslandkarte-python-data:
