version: "3.4"
services:
  python:
    environment:
      - WISSENSLANDKARTE_DOMAINS="['python']"
  integration-test1:
    build:
      context: ./test/integration-test1
      dockerfile: Dockerfile
    depends_on:
      - python
