version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WISSENSLANDKARTE_DOMAINS="['www.example.com','example.com']"
    volumes:
      - "/app/wissenslandkarte/data"
    ports: 
      - "8000:8000"
