name: test-integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test-reachability
        run: ./run-integration-test-1.sh
      - name: test-selenium
        run: ./run-selenium-test-1.sh
